language: python
install:
    - "sudo apt-get update && sudo apt-get -qq install inkscape libatlas-dev"
    - "sudo apt-get build-dep python-scipy"
    - "pip install -q cython scipy"
    - "pip install -r requirements.txt --use-mirrors"

script: ./.travis-test.sh

branches:
    only:
        - docs
